# Generated by Django 4.2.6 on 2023-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "admin"), (2, "staff"), (3, "students")],
                default=2,
                max_length=50,
            ),
        ),
    ]
